# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

workspace 'FinalProject'

target 'FinalProject' do
#    pod 'CVCalendar', '~> 1.2.9'

end

target 'FinalProjectTests' do

end

target 'FinalProjectUITests' do

end

